In [1]:
# Imports

import pandas as pd
import numpy as np
print("imports Done")

imports Done

In [2]:
ip_arr =  [
             'a_example.in',
#            'b_should_be_easy.in',
#            'c_no_hurry.in',
#            'd_metropolis.in',
#            'e_high_bonus.in' 
   ]

INPUT_FILE_NAME = 'data/' + ip_arr[0]
print(f"Taking the input file as {INPUT_FILE_NAME}")

ip_file = open(INPUT_FILE_NAME, 'r')
ip_data = ip_file.read()
ip_file.close()


# Now formatting the data
ip_data = ip_data.split('\n')
header_row = ip_data[0].split(' ')
del ip_data[0]
# ip_data = '\n'.join(ip_data)

# print(ip_data)

i = 0
while i < len(ip_data):
    ip_data[i] = ip_data[i].split(' ')
    i += 1


if(len(ip_data[(len(ip_data)-1)]) == 1):
    print("Deleting the last row")
    del ip_data[len(ip_data) - 1]


# The final data
# print("The final data is")
# print(header_row)
# print(ip_data)

rides = pd.DataFrame(ip_data, dtype=np.int64,columns=['start_x', 'start_y', 'end_x', 'end_y', 'earliest_start', 'latest_finish'])

rides = rides.apply(pd.to_numeric)
rides.head()

Taking the input file as data/a_example.in
Deleting the last row

   start_x  start_y  end_x  end_y  earliest_start  latest_finish
0        0        0      1      3               2              9
1        1        2      1      0               0              9
2        2        0      2      2               0              9

In [3]:
CONFIG = {
    'GRID_X': '',
    'GRID_Y': '',
    'VEHICLES': '',
    'RIDES': '',
    'BONUS': '',
    'STEPS': ''
}

index = 0

for i in CONFIG: 
    CONFIG[i] = np.int64(header_row[index])
    index += 1


CONFIG['STEPS_DONE'] =  0
    
print(f"The config is: \n\n {CONFIG}")

The config is:

 {'GRID_X': 3, 'GRID_Y': 4, 'VEHICLES': 2, 'RIDES': 3, 'BONUS': 2, 'STEPS': 10, 'STEPS_DONE': 0}

# Time to create the vehicles

In [4]:
# Creating the vehicles.
vehicles = []

for i in range(CONFIG["VEHICLES"]):
    vehicles.append({
        "rides": [],
        "steps": 0,
        'location_x': 0,
        'location_y': 0,
        'score': 0,
        'booked': False
    })

    
vehicles = pd.DataFrame(vehicles)


# To update a value in a df

# vehicles.at[1, 'score'] = 23
# vehicles.loc[1]['rides'].append(1)

# Access row by index
# vehicles.loc[1]
vehicles.head()

   booked  location_x  location_y rides  score  steps
0   False           0           0    []      0      0
1   False           0           0    []      0      0

In [8]:
left_rides = []

for index, row in rides.iterrows():
    # The idea is this. If it makes sense, allot the ride to the vehicle and 
    # then end the ride and mark the ride as done and then update the coordinates
#     break
    score = 0
    coord_x = np.zeros((len(vehicles)))
    coord_y = np.zeros((len(vehicles)))
    
    coord_x += row['start_x']
    coord_y += row['start_y']
        
    # Now find the nearest cab from the start point. 
    
    distances = np.abs(coord_x - vehicles['location_x']) + np.abs(coord_y - vehicles['location_y'])
    print(f"the distances are :::  {distances}")
    
    min_distance = np.min(distances)
    print(f"min :  {min_distance}")
    
    min_distance_index = np.where(distances == min_distance)
    print(f"The min index array is  {min_distance_index}")
    
    if len(min_distance_index[0]) == 0: 
        left_rides.append(index)
        continue
    
    vehicle_index = min_distance_index[0][0]
    print(f"The min index is  {vehicle_index}")
    
    # We now have the vehicle. Time to assign the ride and make the trip
    
    distance_to_travel = abs(row['start_x'] - row['end_x']) + abs(row['start_y'] - row['end_y'])
    
    print(f"The distance to travel is {distance_to_travel} and the latest_finish is {row['latest_finish']}")

    if distance_to_travel <= row['latest_finish']:
        print(f"We are taking this ride with the vehicle {vehicle_index}")
        
        # Need to update the vehicles object
                
        score += distance_to_travel
        if min_distance <= row['earliest_start']:
            score += CONFIG["BONUS"]
            print(f"Eligible for BONUS with updated score ::  {score}")
        
        vehicles.at[vehicle_index, 'score'] += distance_to_travel
        vehicles.at[vehicle_index, 'location_x'] = row['end_x']
        vehicles.at[vehicle_index, 'location_y'] = row['end_y']

        vehicles.loc[vehicle_index]['rides'].append(index)
        CONFIG['STEPS_DONE'] += min_distance + distance_to_travel 


    else:
        print("We are leaving this ride")
        left_rides.append(index)
        continue
#     break

the distances are :::  0    0.0
1    0.0
dtype: float64
min :  0.0
The min index array is  (array([0, 1]),)
The min index is  0
The distance to travel is 4 and the latest_finish is 9
We are taking this ride with the vehicle 0
Eligible for BONUS with updated score ::  6
the distances are :::  0    1.0
1    3.0
dtype: float64
min :  1.0
The min index array is  (array([0]),)
The min index is  0
The distance to travel is 2 and the latest_finish is 9
We are taking this ride with the vehicle 0
the distances are :::  0    1.0
1    2.0
dtype: float64
min :  1.0
The min index array is  (array([0]),)
The min index is  0
The distance to travel is 2 and the latest_finish is 9
We are taking this ride with the vehicle 0

In [6]:
rides.head()

   start_x  start_y  end_x  end_y  earliest_start  latest_finish
0        0        0      1      3               2              9
1        1        2      1      0               0              9
2        2        0      2      2               0              9

In [9]:
vehicles.head()

   booked  location_x  location_y      rides  score  steps
0   False           2           2  [0, 1, 2]      2      0
1   False           0           0         []      0      0